### ISSUE TITLE
Unlink

### ISSUE THREAD

**Issue by Allann** [simple-odata-client/Simple.OData.Client#194]
Hey people, 

So my 2 days of pain can benefit everyone I hope.  Here are the details of my findings:

The problem we had was a routing issue.  All the tests here against Unlink seem to send a URI to WCF service not a Web API.
This has come about by reading the specifications of OData, which clearly state that a relative path may be used in the query options for deletions.  
A URI resembling the following would be sent: http://host/entity(id)/navProperty/$ref?$id=navProperty(key)

This is correct, and is a valid _relative_ path for a wcf service.  Eg. http://host/service.svc

HOWEVER

This is not a valid _relative_ path for an ASP Web API. Eg. http://host/
Therefore, the WebAPI had no idea what to do with a URI using a relative path.
To get this working with a Web API you must pass a fully qualified URI in the query options like this: http://host/entity(id)/navProperty/$ref?$id=http://host/navProperty(key)

This very small difference allows the Web API to properly find a route, which must be defined in your controller as follows:

//Actual web request URL will look like: http://host/Teachers(key)/Students/$ref?$id=http://host/Students(studentId)
        [HttpDelete]
        [ODataRoute("Teachers({key})/Students({studentId})/$ref")]
        public IHttpActionResult RemoveStudentWithId([FromODataUri] Guid key, [FromODataUri] Guid studentId)
        {
            return Ok("Teachers(" + key + ")/Students(" + studentId + ")");
        }

When I say Web API I mean an ODataController based webservice class.  I can provide a sample test project if needed.

**Comment by object** [comment]
Thank you for your finding. Do you mean that Simple.OData.Client must always send fully qualified URIs in Link/Unlink operations? I am afraid this can break other scenarios, because one of the issues I received was specifying absolute URI in some (not related to this) scenarios which caused troubles when OData service runs on in a load balanced environment and client may not know the actual physical host name.

**Comment by AlexaHLE** [comment]
@Allann, was what you read about relative paths in deletions specific to deleting references? As I mentioned in #70, as far as I can tell the OData v4 spec requires a full path when deleting a $ref. 

This would mean that the ASP ODataController method DeleteRef shown at the bottom of [This Guide](http://www.asp.net/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/entity-relations-in-odata-v4) is correct in expecting a full path id.

**Comment by Allann** [comment]
Sorry, been flat out at work.
Vagif, I understand you may be caught between a rock and a hard place relating to the load balancing. I must admit not to know too much about that, but find it hard to believe the client needs to know what host to call too.  The OData settings already has the base address already and is making calls to a full uri, how is this different?  I thought a call to a url would be managed by the Load balancing infrustructure?  By not including the full url we can't use the routing and thereby prevent the delete from occuring.  Is there a way we can intercept this call and and change the url ourselves then?
@AlexaHLE yes.  specifically where a many-to-many relationship uses an intermediate table to store the references.  The only way to such a relationship is by using the Delete Ref feature.
