### ISSUE TITLE
Unable to use Simple.OData.Client in ASP.NET MVC application

### ISSUE THREAD

**Issue by pavel-hi** [simple-odata-client/Simple.OData.Client#24]
I tried to do a simple example from Getting Started tutorial using MVC application. Here is the action method of a controller:

```
public ActionResult Index()
{
    var client = new ODataClient("http://packages.nuget.org/v1/FeedService.svc/");
    var packages = client.FindEntries("Packages?$filter=Title eq 'Simple.OData.Client'");

    return View();
}
```

After "client.FindEntries" is fired application is hanging with no response.

I also checked the behaviour in Console application with the same code (first two lines of the action method above) and it turned out that it works fine without any problems getting results from a remote endpoint.

Could you check please what the problem is?

**Comment by ashuthinks** [comment]
I'm still uable to use it :(
I tried with simple example 
   public ActionResult Index()
        {
            ODataClient client = new ODataClient("http://localhost:55500/Dev/");
            var languages = client.For<AllLanguage>().FindEntriesAsync().result;
       
            return View();
        }

Before executing and getting all languages it goes to return View() :(

and I do not get any data , please help me.

**Comment by gnaresh82** [comment]
You have to wrap that client call inside a task.

var client = new ODataClient("http://localhost:6025/odata");

                     var res = Task.Run(async () =>

                    {

                        var list =

                           await client.For<QueryableCustomer>()

                               .Filter(x => x.CustomerID == 10)

                               .FindEntriesAsync();

                        return list.FirstOrDefault();

                    }).GetAwaiter().GetResult();

Thsnks,
Naresh

**Comment by ramon26cruz** [comment]
Hi I try to use the Simple OData but I get error

var client = new ODataClient("http://packages.nuget.org/v1/FeedService.svc/");
var packages = await client.FindEntriesAsync("Packages?$filter=Title eq 'Simple.OData.Client'");
foreach (var package in packages)
{
      Console.WriteLine(package["Title"]);
 }

Here is the errro that I get

Error	1	The 'await' operator can only be used within an async method. Consider marking this method with the 'async' modifier and changing its return type to 'Task'.
