### ISSUE TITLE
ANY / ALL doesn't work in filters for scalar collection fields - expects it to be navigation property

### ISSUE THREAD

**Issue by Jason-Aylesworth** [simple-odata-client/Simple.OData.Client#274]
In the endpoint metadata, ScalarCollectionField is declared as follows:

```
<Property Name="ScalarCollectionField" Type="Collection(Edm.String)" Nullable="false"/>
```

Filtering against this field using the OData API directly works fine:

```
http://server/EntityName?$select=ScalarCollectionField&$filter=ScalarCollectionField/any(a: a eq 'vacation')
```

Using Simple.OData.Client library returns an error:

```
var client = new ODataClient(settings);
var x = ODataDynamic.Expression;

var values = client.
    For(x.EntityName).
    Filter(x.ScalarCollectionField.Any(x == "vacation")).
    Select(x.ScalarCollectionField).
    FindEntriesAsync().
    Result;
```

Error: "Navigation property [ScalarCollectionField] not found"

**Comment by zivillian** [comment]
I had the same error, and was even able to reproduce this using the [TripPinService](http://services.odata.org/V4/TripPinService)

For example this request
[http://services.odata.org/V4/TripPinService/People?$filter=AddressInfo/any(x: x/City/Region eq 'WA')](http://services.odata.org/V4/TripPinService/People?$filter=AddressInfo/any(x:%20x/City/Region%20eq%20%27WA%27))
returns a single Person result

Trying the same using Simple,OData results in the mentioned UnresolvableObjectException `Association [AddressInfo] not found`

Here's the code I used to reproduce this:

```
var persons = await _client
                .For<Person>()
                .Filter(x => x.AddressInfo.Any(a => a.City.Region == "WA"))
                .FindEntriesAsync();
```

**Comment by object** [comment]
Thanks for these examples. I should be able to resolve it now.

**Comment by Echarnus** [comment]
Any news on this one?
