### ISSUE TITLE
Retrieve data when service's entity name differs from app model's name.

### ISSUE THREAD

**Issue by richardalmonte** [simple-odata-client/Simple.OData.Client#337]
Hi,

I'm trying to consume a service where the entities names differs from my data model classes's... 
I'm using the client as "Typed" so when trying to retrieve the data it throws an exception because the class name is not found. 

So, there is a way to use some Attribute that indicates the client that the Service Entity name is different from the model class name?

Thanks.

**Comment by object** [comment]
Yes, you can override the class name. Just use the name of the OData resource type, e.g.:

client.For<Customers>("CustomerResource").Where(...).FindEntriesAsync(...)

Hope this helps.

**Comment by richardalmonte** [comment]
Hi, 

This library uses some attributes (Annotations)? if yes, there's a documentation, where?

I'm trying to use some class/Properties attributes to indicate how the class must be serialized/deserialized and/or indicate to ignore some properties but, I can't find any documentation about it.
