### ISSUE TITLE
Calling function, no good method for executing with single element return type

### ISSUE THREAD

**Issue by NetTecture** [simple-odata-client/Simple.OData.Client#380]
I am calling a function in OData v4 that is returning a complex type.

THere is no easy way to do that, particualrly with async.

* ExecuteAsSingleAsync does not allow to set the return type. Calling that on a bound function returns the type it is bound to -> wrong.

* .ExecuteAsArrayAsync<T>()) works, but returns an array. That means wrapping the await in () and then doing FirstOrDefault or Single on it. This is programming-clumsy.

* ExecuteAsScalarAsync tries to get the first property of the defined return type and cast the whole return type to it. Error.

What is missing is a simple 

ExeuteAsSingleAsync<T> which accepts the type parameter for the return type. Or getting ExecuteAsScalarAsync working properly.

The ExecuteAsScalarSync error looks like this:

Defined Metadata of function:

<Function Name="Snapshot" IsBound="true">
<Parameter Name="bindingParameter" Type="Reflexo.Api.TrdConnection"/>
<Parameter Name="Symbol" Type="Edm.String" Unicode="false"/>
<ReturnType Type="Reflexo.Api.TrdInstrumentSnapshot"/>
</Function>

The call like this:

            var snapshot = await client.For<Reflexo.Api.TrdConnection>()
                .Key(apiProvider.Identity)
                .Function("Snapshot")
                .Set(new { Symbol = model.Code.Replace("/", "!") })
                .ExecuteAsScalarAsync<Reflexo.Api.TrdInstrumentSnapshot>();

returns:

Server Error in '/' Application.

Unable to convert value from type System.DateTimeOffset to type Reflexo.Api.TrdInstrumentSnapshot

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.FormatException: Unable to convert value from type System.DateTimeOffset to type Reflexo.Api.TrdInstrumentSnapshot

The first property in InstrumentSnapshot is a DateTime. Looks like it takes this and tries to cast it into the complete return type.

This code works fine, but as I said - it is clumsy, the brackets breaking the fluent flow (and it allocates a surplus array):

**Comment by object** [comment]
Thank you for raising the issue. The whole OData function concept is sort of a hack in the current version. I am reworking it for the version 5 (release date still not set). It should take care of such defects then.

**Comment by NetTecture** [comment]
Turns out a long time later - not your problem ;) The problem was the backend - webapi odata did not encapsulate scalar values in an odata value construct, so the deserialization blow. Updating to nightly (at this point) 7.4 it works - because at this point (asp.net core) they decided to acutally return that in a odata json structure with value property.

Works.
