### ISSUE TITLE
Key value empty on URL when using UpdateEntryAsync

### ISSUE THREAD

**Issue by MatthewHinds** [simple-odata-client/Simple.OData.Client#404]
Hi there,

I've receiving the following 404 error whenever executing "UpdateEntryAsync".
"Simple.Odata.Client.WebRequestException: 'Not Found'.

I checked my odata insights telemetry and it's producing the following:

> Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Request","time":"2017-06-10T05:28:03.6331620Z","tags":{"ai.internal.sdkVersion":"web:2.3.0-1223","ai.internal.nodeName":"DESKTOP","ai.operation.id":"HnVW4A9ISEg=","ai.location.ip":"::1","ai.cloud.roleInstance":"DESKTOP","ai.operation.name":"PATCH p_payee [odataPath]"},"data":{"baseType":"RequestData","baseData":{"ver":2,"id":"HnVW4A9ISEg=","name":"PATCH p_payee [odataPath]","duration":"00:00:00.0014986","success":false,"responseCode":"404","url":"http://localhost:56586/odata/p_payee()","properties":{"DeveloperMode":"true"}}}}

The code I'm using is the following:

```c#
            var client = new ODataClient(new ODataClientSettings { BaseUri = serviceUri, RenewHttpConnection = true });
            await client
                .For<PayeeModel.p_payee>()
                .Key(newPayee.payee_id)
                .Set(new { first_name = "Test" })
                .UpdateEntryAsync();
```

It would seem that the Key value is not passing in. I've tried hard coding it but there is no luck.
Please let me know if you have any questions.

**Comment by object** [comment]
Sorry for the late response. How does your metadata for p_payee look? Does the entity definition include the key? You can also try to rewrite the query by removing Key clause and inserting Where clause with key field assignment. Then check in Fiddler that it transforms the request into the one with the key. If not, then most likely metadata definition lack key declaration for payee_id.
