### ISSUE TITLE
Alternate Key support

### ISSUE THREAD

**Issue by hrnt** [simple-odata-client/Simple.OData.Client#421]
There is an extension/community vocabulary to OData 4.0 (adopted in 4.01) for specifying additional keys for entity types. 

For example, Person with database ID 1234 could be referred by its database ID and its SSN: People(1234) and People(SSN='12345').

Right now it seems that there is no way of referring to this record using the alternate key syntax (I might have missed something, of course). 

I took a quick look at the code, and it seems that there are at least two things blocking this from working:

- The parameter of Key(IDictionary<string,object>) is filtered to only include keys that were specified in the metadata (FluentCommand.cs). There could either be a mechanism of overriding this (always use these keys, no matter what the metadata says), or the metadata parser should be able to parse the Alternate Key annotations.

- If there is only a single named key, the name of the key is never included in the URL (CommandFormatterBase.cs). The alternate key name is required to disambiguate between the primary key and the alternate keys.

Here are a couple of relevant links.

https://issues.oasis-open.org/browse/ODATA-798
http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_AlternateKeys

**Comment by object** [comment]
Thank you for the information and links. I am adding this one to the roadmap.

**Comment by object** [comment]
Released in 5.11.
