### ISSUE TITLE
Introduce $apply for fluent interface

### ISSUE THREAD

**Issue by mariohines** [simple-odata-client/Simple.OData.Client#490]
I've recently been playing with $apply and have run into the limitation of Simple.OData.Client not have a Fluent interface to utilize it (or the documentation doesn't exist). I've found a way around it, but it has some caveats that don't quite match the OData spec, but it works. Just hoping that adding $apply, along with the aggregation features could be a future enhancement. (Actually looking to contribute that...just not sure where to begin)

**Comment by object** [comment]
That would a great addition to the library. The main focus recently has been on supporting NETStandard 2.0 and .NET Core, with a very few new features added. Adding apply with aggregations would fill the gap between the OData4 specification and Simple.OData.Client V4 adapter.

If you are willing to contribute, I'd suggest to go through the library unit tests first. The library has pretty good test coverage with more than a thousand tests. Fluent interfaces reside in the Fluent folder of the core library, and they all have tests for them. Recent version mocks HTTP calls so you don't need to set up OData service on your machine while running the tests.
