### ISSUE TITLE
Poor Performance Issues during response deSerialization  

### ISSUE THREAD

**Issue by raviraj1976** [simple-odata-client/Simple.OData.Client#497]
We are using the latest  Simple.OData.Client 5.2.2  version.  There is a severe performance issues when the record count goes up.
In our Scenario, for 12000 records,  Simple.OData.Client takes more than 1 minute . If we watch the fiddler call, OData calls completes in 10 seconds.  We found that the following code in ResponseReader takes good amount of time.

 private ODataResponse ReadResponse(ODataReader odataReader)
        {
            ResponseNode rootNode = null;
            var nodeStack = new Stack<ResponseNode>();

            while (odataReader.Read())
            {
                if (odataReader.State == ODataReaderState.Completed)
                    break;

                switch (odataReader.State)
                {
                    case ODataReaderState.ResourceSetStart:
                        StartFeed(nodeStack, CreateAnnotations(odataReader.Item as ODataResourceSet));
                        break;

                    case ODataReaderState.ResourceSetEnd:
                        EndFeed(nodeStack, CreateAnnotations(odataReader.Item as ODataResourceSet), ref rootNode);
                        break;

                    case ODataReaderState.ResourceStart:
                        StartEntry(nodeStack);
                        break;

                    case ODataReaderState.ResourceEnd:
                        EndEntry(nodeStack, ref rootNode, odataReader.Item);
                        break;

                    case ODataReaderState.NestedResourceInfoStart:
                        StartNavigationLink(nodeStack, (odataReader.Item as ODataNestedResourceInfo).Name);
                        break;

                    case ODataReaderState.NestedResourceInfoEnd:
                        EndNavigationLink(nodeStack);
                        break;
                }
            }

            return ODataResponse.FromNode(rootNode);
        }

We end-up using both Simple.OData.Client GetCommandTextAsync() for the ODATA expression builder from Linq expression and HttpClient for execution which just takes 12 seconds for 12000 records.

It would be a great help if you could expose a public method ExecuteAsync in BoundClient<T> which returns Task<HttpResponseMessage>.
 partial class BoundClient<T>
    {
      public Task<HttpResponseMessage> ExecuteAsync()
        {            
        }
  }

 This will help us to use JsonConvert.DeserializeObject   from Newtonsoft.Json or any better library for DeSerialization of HttpResponseMessage as shown below. 
--------------------------------------------------------------------
 /// <summary>
    /// class JsonHelperExtensions
    /// </summary>
    public static class JsonHelperExtensions
    {
        public static async Task<List<T>> DeserializeHttpResponseMessage<T>(this Task<HttpResponseMessage> tasKHttpResponseMessage)
        {
            var httpResponseMessage = await tasKHttpResponseMessage.ConfigureAwait(false);

            string content = await httpResponseMessage.Content.ReadAsStringAsync().ConfigureAwait(continueOnCapturedContext: false);

            return JsonConvert.DeserializeObject<ODataResponse<List<T>>>(content).Value;
        }
}

    public class ODataResponse<T>
    {
        [JsonProperty("@odata.context")]
        public string ODataContext { get; set; }

        public T Value { get; set; }
    }   

Appreciate your help!

**Comment by object** [comment]
Thank you so much for the investigation. I am away until Sunday but will work on this when I am back next week.

**Comment by object** [comment]
@raviraj1976 I want to thoroughly investigate this and possible other performance problems (and your suggestion to use JSON.NET is one of the options), but I need a reference result set to run benchmarks. Is it possible for you to send me OData payload for result set with 1000+ records, and in addition a service metadata file? Then I can mock HTTP communication and benchmark result parsing.
Basically I need:
1. HTTP response payload (can be obtained using Fiddler or other tools, 1000 records should be enough but I don't mind 10K either).
2. OData service metadata file (available at <service_url>/$metadata endpoint).
If response contains sensitive information, perhaps you can obfuscate it.
You can send this to vagif.abilov at gmail.

Thanks in advance.

**Comment by object** [comment]
Also, would it be sufficient if the library expose settings custom response reader in ODataClientSettings? Currently response is read by one of OData adapters (either V3 or V4), and the code looks like this:

```
                        var responseReader = _session.Adapter.GetResponseReader();
                        return createResult(await responseReader.GetResponseAsync(response).ConfigureAwait(false));

```
this code returns Func<ODataResponse, T> where T is a client POCO type.
Will this work for you?

**Comment by raviraj1976** [comment]
This will work for me as long as I can use JSON.Net or any other for
Deseiralization. HttpResponseMessgae as a out put result is straight
forward since it contains the entire case Brent. Otherwise I may have to
iterate through the response reader since all the data will not be
available at once.

I can send the metadata & Json result only on your email and will not post
it on sites.

Thanks & Regards
Raviraj

**Comment by object** [comment]
I will check what does it takes to make response reader (i.e. HttpResponseMessage converter) pluggable. You can send me the requested information to vagif.abilog@gmail.com

**Comment by raviraj1976** [comment]
Tried to create an example using http://services.odata.org/V4/Northwind/Northwind.svc/$metadata.  This doesn't have enough data. when tried to send an email to  vagif.abilog@gmail.com , bounced with an error saying address not found.

**Comment by object** [comment]
Sorry, my address is vagif.abilov@gmail.com

**Comment by object** [comment]
My mistake

**Comment by object** [comment]
BTW, what else you can do it the following:

```
            var clientRequest = await client
                .For<Transfers>()
                .Filter(x => some filter)
                .BuildRequestFor()
                .FindEntriesAsync();
            var clientResponse = await clientRequest.RunAsync();
            var responseMessage = clientResponse.ResponseMessage;

```
ResponseMessage is an actual HttpResponseMessage that you can process instead of letting SOD call slow Microsoft libraries.

Hope this helps.

**Comment by jafin** [comment]
Thanks @raviraj1976 , we were having significant performance issues with the OData deserialization, average batch size was 12,000 items,  wire time was approx 1sec, deserialization took approx 6seconds.   Changed to JsonConvert to deserialize and total return time now 1.5sec      For a batch run of 10 queries, OData serializer took 82 seconds, JsonConvert = 12 seconds.

**Comment by phatcher** [comment]
@jafin I presume that the data structure is relatively simple i.e. contains no subtypes etc?

**Comment by raviraj1976** [comment]
In our case we had subtypes and the performance improved post using JsonConvert for deserialuzation.

**Comment by phatcher** [comment]
@raviraj1976 Thanks for that, I'll need to do some experiments - I would have thought that OOB JsonConvert wouldn't know how to interpret the odata annotations required to select the appropriate subtype etc.

If you have the time, have another go with the latest Simple.OData.Client codebase (no nuget as yet) as I've done some optimisation on the [deserialization](https://github.com/object/Simple.OData.Client/issues/512) - there's a few more bits to do, but I had large improvement in performance.

**Comment by jafin** [comment]
@phatcher I think the structure had only a few subtypes. I'll checkout the current code and see if there is any change.

**Comment by object** [comment]
@jafin while there are several improvement on the, thanks to the work being done by @phatcher I suspect that the major performance loss is attributed to Microsoft.OData.Edm parser, especially since the release of the version 7.x. I recently started building performance benchmark results and would like to compare performance of the previous version of Simple.OData.Client that used ODataLib 6 with the new version to get a better idea about differences. But you will never have performance close to the performance of JSON serialiser that is not aware of OData-specific nuances. If you want to prioritise performance of large batches, the best you can do is issue HTTP requests using our library, receive response as a stream (you can do it with Simple.OData.Client) and apply a deserialiser of your choice to that stream. Since you control data schema, you can handle it as efficient as it can be.

**Comment by jafin** [comment]
@object I'd prefer _NOT_ to use the Json Deserializer for the fact of missing out on the correct parsing of the schema.  We are just trying to minimize the time our Xamarin client is tasking to performing an initial data load, and noticed that wire time was not the problem,  using the _hack_ for the Json serializer speed things up by a huge factor.   

I have run @phatcher's features/512_metaline line (00bfe7b42c7330d452af65ba106bdbcd2b528dff)  and it has made a significant performance improvement.   (I also tried the Object\v5 branch (194744cd4ba8175afafc0cd546a21bd6c6193160) but noticed no real change. 

I'd love to see those changes merged in, would be awesome!.

**Simple.Odata client 5.4**

```

// * Summary *

BenchmarkDotNet=v0.11.1, OS=Windows 10.0.16299.547 (1709/FallCreatorsUpdate/Redstone3)
Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
Frequency=3515624 Hz, Resolution=284.4445 ns, Timer=TSC
  [Host]     : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3130.0
  Job-GBSWSC : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3130.0

IterationCount=10  LaunchCount=1  WarmupCount=1  



                                   Method |    Mean |    Error |   StdDev |
----------------------------------------- |--------:|---------:|---------:|
 'Simple OData use internal Deserializer' | 7.671 s | 0.3987 s | 0.2372 s |
 'Simple OData use Json.Net Deserializer' | 1.269 s | 0.0596 s | 0.0394 s |
       'Microsoft.OData DataServiceQuery' | 4.686 s | 0.1362 s | 0.0811 s |

```

**tip OData Client features/512_Metadata**

```
IterationCount=10  LaunchCount=1  WarmupCount=1  

                                   Method |    Mean |    Error |   StdDev |
----------------------------------------- |--------:|---------:|---------:|
 'Simple OData use internal Deserializer' | 1.754 s | 0.1355 s | 0.0896 s |
 'Simple OData use Json.Net Deserializer' | 1.286 s | 0.0313 s | 0.0186 s |
       'Microsoft.OData DataServiceQuery' | 4.843 s | 0.2032 s | 0.1209 s |

```
The performance is near inline with the native Json.Net Deserializer!

**Comment by object** [comment]
@jafin thank you for these benchmarks. They indeed show that we should apply @phatcher's changes ASAP. I will try to do this during the weekend.

**Comment by object** [comment]
@phatcher can you send me a PR with your improvements?

**Comment by phatcher** [comment]
@object Will do, have some other improvements I want to kick in first, should save a few million more calls :-)

**Comment by object** [comment]
Terrific!

**Comment by raviraj1976** [comment]
Microsoft released "5.8.4" version which includes the performance fix?

<package id="Microsoft.Data.Edm" version="5.8.4" targetFramework="net452" />
  <package id="Microsoft.Data.OData" version="5.8.4" targetFramework="net452" />
  <package id="System.Spatial" version="5.8.4" targetFramework="net452" />

**Comment by object** [comment]
@raviraj1976 was there any information about performance differences?

BTW there is 5.5.0-beta2 Nuget package which include Paul's performance improvements.

**Comment by raviraj1976** [comment]
We are yet to pull 5.5.0-beta2. I will keep you posted

**Comment by raviraj1976** [comment]
> BTW, what else you can do it the following:
> 
> ```
>             var clientRequest = await client
>                 .For<Transfers>()
>                 .Filter(x => some filter)
>                 .BuildRequestFor()
>                 .FindEntriesAsync();
>             var clientResponse = await clientRequest.RunAsync();
>             var responseMessage = clientResponse.ResponseMessage;
> ```
> ResponseMessage is an actual HttpResponseMessage that you can process instead of letting SOD call slow Microsoft libraries.
> 
> Hope this helps.

Quick question.

Can we  use   .BuildRequestFor() with FindEntryAsync()? We found an issue using BuildRequestFor() with FindEntryAsync() with 5.4 version.   With BuildRequestFor(), FindEntryAsync returns multiple row and without it, it returns a single record.

Any thoughts?

Thanks & Regards
Raviraj

**Comment by object** [comment]
Hmm, BuildRequestFor doesn't know whether you will retrieve all results or just the first one. It just converts specified clauses to OData request. But you can use Top clause to make it a part of the request.

**Comment by phatcher** [comment]
@jafin I'd appreciate it if you could re-run your benchmark with the 5.5 release as it should be even better than your previous results

**Comment by raviraj1976** [comment]
Thank you for the information. Just curious why the version shows 0.0.0.0 with Simple.OData.Client.5.4.0? and why the dependent assemblies(Simple.OData.Client.Dynamic.dll, Simple.OData.Client.V4.Adapter.dll,  
Simple.OData.Client.V3.Adapter.dll , Microsoft.OData.Core,Microsoft.Data.OData,  are not copied to the target bin folder along with Simple.OData.Client.Core.dll?

<Reference Include="Simple.OData.Client.Core, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Simple.OData.Client.5.4.0\lib\net452\Simple.OData.Client.Core.dll</HintPath>
    </Reference>
    <Reference Include="Simple.OData.Client.Dynamic, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Simple.OData.Client.5.4.0\lib\net452\Simple.OData.Client.Dynamic.dll</HintPath>
    </Reference>
    <Reference Include="Simple.OData.Client.V3.Adapter, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Simple.OData.Client.5.4.0\lib\net452\Simple.OData.Client.V3.Adapter.dll</HintPath>
    </Reference>
    <Reference Include="Simple.OData.Client.V4.Adapter, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Simple.OData.Client.5.4.0\lib\net452\Simple.OData.Client.V4.Adapter.dll</HintPath>
    </Reference>

**Comment by object** [comment]
@raviraj1976 There was a bug in 5.4 (and a few earlier versions) that resulted in empty assembly version.
And when it comes to dependent assemblies, because Simple.OData.Client.Core doesn't have dependencies on specific OData protocol (it loads them at runtime depending on the OData service version), when you include a reference to just this assembly, corresponding adapter and Microsoft OData assemblies are not copied automatically. You have to either add a NuGet package or reference them manually.

**Comment by taspeotis** [comment]
Hi @phatcher, I'm working with @jafin on this issue. We appreciate your efforts to improve performance. Having tested with v5.5 I can say deserialization is still unfortunately slow.

Profiling what `ODataClient` is doing when it's receiving our message (about 2,500 entities, but there are some collections so I'd say about 25,000 entities total) there are ~70,000 calls to `IsNotMapped`.

The implementation is:

```
return member.GetCustomAttributes().Any(x => x.GetType().Name == "NotMappedAttribute");
```

I did a quick-and-dirty cache:

```
[ThreadStatic] private static IDictionary<MemberInfo, bool> _memberInfos;

public static bool IsNotMapped(this MemberInfo member)
{
    if (_memberInfos == null)
        _memberInfos = new Dictionary<MemberInfo, bool>();

    if (!_memberInfos.TryGetValue(member, out var result))
    {
        result = member.GetCustomAttributes().Any(x => x.GetType().Name == "NotMappedAttribute");

        _memberInfos.Add(member, result);
    }

    return result;
}
```

And performance was improved by about a third - 2.27s spent deserialising reduced down to 1.49s.

Someone else called out the performance of `IsNotMapped` [over here](https://github.com/object/Simple.OData.Client/issues/323#issuecomment-267111824), among other reflection-based things.

**Comment by phatcher** [comment]
@taspeotis Have a look at my features/479_TypeCache branch (see #562) as I've implement the cache you mentioned along with some other bits.

The amortized call time for IsNotMapped is reduces to about ~20% of the original on my benchmarks

**Comment by taspeotis** [comment]
@phatcher Thank you for your work on this, we use Simple.OData.Client in a mobile application which I will probably end up working some more on over the next few months. I'll incorporate it and report back but it might be a little while.

**Comment by phatcher** [comment]
@taspeotis No problem, BTW you can grab from the main v5 branch now as it has been merged in and there will likely be more stuff in there as well by the time you test it

**Comment by phatcher** [comment]
Closing as I think we've address the issues raised here, any more performance issues raise a specific issue
