### ISSUE TITLE
Dynamic container property name

### ISSUE THREAD

**Issue by phatcher** [simple-odata-client/Simple.OData.Client#564]
@object Currently if you want to use an open type and return the properties you must pass the dynamic container name as part of the command.

The problem arises when you want to expand relations of this entity which are themselves open types, since there's no way of telling the interior calls what to use.

With the introduction of ITypeCache we can add a Register<T> method which can take the dynamic properties container name and then this can be retrieved in the ToObject from wherever it is called.

Additionally, we can extend ITypeCache with an ITypeConverter property which allows registration/retrieval of custom converters - this then allows for different converters per OData schema.

This should address #360 and #365

The public changes to the API are to expose an ITypeCache on the ODataClientSetttings class - this provides an entry point to the appropriate objects which are created behind the scenes.

Can you take a look at this and see if you're happy with the proposed changes - I've tried to ensure they are non-breaking for v5 but marked some as obsolete ready for v6.  I also need a few more tests but I want to ensure the API is acceptable first

**Comment by object** [comment]
Sorry for the late response. Can you give an example of how the revised API will look, also some code examples of how the client would use it? And if this helps addressing issues you mentioned, can you think of tests we can add to verify they are addressed?

**Comment by phatcher** [comment]
@object The current code is on [564_ContainerName](https://github.com/object/Simple.OData.Client/compare/master...phatcher:features/564_ContainerName), I still need to write some tests but I need to make sure you like the direction of the API changes...

Basic changes are...

1. Introduce `ITypeConverter` which has the same signature as CustomConverters but is per OData schema
2. Extend ITypeCache with `Register` methods, which can take the container name and also expose the relevant `ITypeConverter` instance.
3. Expose the relevant `ITypeCache` on `ODataClientSettings`, this allows us access to the registration of both container names and custom converters on a per schema basis

Remainder are adjustments to `ToObject` etc as we don't pass the container name anymore but retrieve it from the `ITypeCache`. I've kept the existing signatures the same so that it if you pass a container name on one of the methods it performs an automatic registration of the type for you.

**Comment by phatcher** [comment]
@object Issued a pull request with the code, take a look and let me know if you need any changes

**Comment by object** [comment]
Thanks Paul, I was off due to Xmas/New year holidays. Will review it shortly.
