### ISSUE TITLE
Simple.OData.Client is not working for collection properties

### ISSUE THREAD

**Issue by nazyf** [simple-odata-client/Simple.OData.Client#582]
I'm using Simple.OData.Client.Net45 version 5.0.0.1 and I get the following error:
The DataServiceContext to which the DataServiceCollection instance belongs could not be determined. 
The DataServiceContext must either be supplied in the DataServiceCollection constructor or be used 
to create the DataServiceQuery or QueryOperationResponse object that is the source of the items in the DataServiceCollection.

My code look like this:
var applications = await client.For<Application>().                              Expand("DesktopGroups").FindEntriesAsync();

<EntityType Name="Application">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Guid" Nullable="false" />
                <Property Name="Name" Type="Edm.String" />
               .....
                <NavigationProperty Name="DesktopGroups" Type="Collection(Citrix.Monitor.Model.DesktopGroup)" />
.....
            </EntityType>

**Comment by object** [comment]
The version 5.0.0.1 is very old. Please update to one of the recent NuGet packages.

**Comment by nazyf** [comment]
When I try to install the latest (5.6.2), I get the following error:
Could not install package 'Simple.OData.Client 5.6.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by object** [comment]
That's correct. .NET 4.6.1 is the minimal supported version now, earlier versions are no longer supported. You can try installing 4.x version of Simple.OData.Client and see if it works. But 5.0.0.1 wasn't working well, you shouldn't use it.

Do you have an option of upgrading your project to .NET 4.6.1?

**Comment by nazyf** [comment]
When I upgrade to .net 4.6.1 I get this error while running:

Could not load file or assembly 'Simple.OData.Client.V4.Adapter' or one of its dependencies. The system cannot find the file specified.
 at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Simple.OData.Client.AdapterFactory.LoadAdapterAssembly(String modelAdapterAssemblyName)
   at Simple.OData.Client.AdapterFactory.LoadModelAdapter(ITypeCache typeCache, String modelAdapterAssemblyName, String modelAdapterTypeName, Object[] ctorParams)

Is there any way to work with .net 4.5?

**Comment by nazyf** [comment]
I also tried now to use the .net 4.6.1. with the Simple.oData.Client 5.6.2. and still the same error:
The DataServiceContext to which the DataServiceCollection instance belongs could not be determined.
The DataServiceContext must either be supplied in the DataServiceCollection constructor or be used
to create the DataServiceQuery or QueryOperationResponse object that is the source of the items in the DataServiceCollection.

**Comment by object** [comment]
That's strange, I am pretty sure something is not properly set up. Do you have a call stack of the exception about DataServiceContext? Also, are you sure this is a client side error and not something thrown at the server?

**Comment by nazyf** [comment]
at Microsoft.OData.Client.DataServiceCollection`1.GetContextFromItems(IEnumerable`1 items)
   at Microsoft.OData.Client.DataServiceCollection`1..ctor(DataServiceContext context, IEnumerable`1 items, TrackingMode trackingMode, String entitySetName, Func`2 entityChangedCallback, Func`2 collectionChangedCallback)
   at lambda_method(Closure , Object[] )
   at Simple.OData.Client.Extensions.DictionaryExtensions.ToObject(IDictionary`2 source, ITypeCache typeCache, Type type, Boolean dynamicObject)
   at Simple.OData.Client.Extensions.DictionaryExtensions.ToObject[T](IDictionary`2 source, ITypeCache typeCache, Boolean dynamicObject)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()

I'm sure it's on my side. The server side is citrix.

**Comment by object** [comment]
Ah, I think it's the classes that you use to retrieve data. How does an entity class look? It's not a simple POCO class, is it?

**Comment by nazyf** [comment]
[global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Application")]
    public partial class Application : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Application object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="applicationType">Initial value of ApplicationType.</param>
        /// <param name="enabled">Initial value of Enabled.</param>
        /// <param name="lifecycleState">Initial value of LifecycleState.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public static Application CreateApplication(global::System.Guid ID,
                    int applicationType,
                    bool enabled,
                    int lifecycleState,
                    global::System.DateTimeOffset createdDate,
                    global::System.DateTimeOffset modifiedDate)
        {
            Application application = new Application();
            application.Id = ID;
            application.ApplicationType = applicationType;
            application.Enabled = enabled;
            application.LifecycleState = lifecycleState;
            application.CreatedDate = createdDate;
            application.ModifiedDate = modifiedDate;
            return application;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property PublishedName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PublishedName")]
        public string PublishedName
        {
            get
            {
                return this._PublishedName;
            }
            set
            {
                this.OnPublishedNameChanging(value);
                this._PublishedName = value;
                this.OnPublishedNameChanged();
                this.OnPropertyChanged("PublishedName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _PublishedName;
        partial void OnPublishedNameChanging(string value);
        partial void OnPublishedNameChanged();
        /// <summary>
        /// There are no comments for Property ApplicationType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ApplicationType")]
        public int ApplicationType
        {
            get
            {
                return this._ApplicationType;
            }
            set
            {
                this.OnApplicationTypeChanging(value);
                this._ApplicationType = value;
                this.OnApplicationTypeChanged();
                this.OnPropertyChanged("ApplicationType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private int _ApplicationType;
        partial void OnApplicationTypeChanging(int value);
        partial void OnApplicationTypeChanged();
        /// <summary>
        /// There are no comments for Property Enabled in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Enabled")]
        public bool Enabled
        {
            get
            {
                return this._Enabled;
            }
            set
            {
                this.OnEnabledChanging(value);
                this._Enabled = value;
                this.OnEnabledChanged();
                this.OnPropertyChanged("Enabled");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private bool _Enabled;
        partial void OnEnabledChanging(bool value);
        partial void OnEnabledChanged();
        /// <summary>
        /// There are no comments for Property AdminFolder in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AdminFolder")]
        public string AdminFolder
        {
            get
            {
                return this._AdminFolder;
            }
            set
            {
                this.OnAdminFolderChanging(value);
                this._AdminFolder = value;
                this.OnAdminFolderChanged();
                this.OnPropertyChanged("AdminFolder");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _AdminFolder;
        partial void OnAdminFolderChanging(string value);
        partial void OnAdminFolderChanged();
        /// <summary>
        /// There are no comments for Property LifecycleState in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LifecycleState")]
        public int LifecycleState
        {
            get
            {
                return this._LifecycleState;
            }
            set
            {
                this.OnLifecycleStateChanging(value);
                this._LifecycleState = value;
                this.OnLifecycleStateChanged();
                this.OnPropertyChanged("LifecycleState");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private int _LifecycleState;
        partial void OnLifecycleStateChanging(int value);
        partial void OnLifecycleStateChanged();
        /// <summary>
        /// There are no comments for Property Path in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Path")]
        public string Path
        {
            get
            {
                return this._Path;
            }
            set
            {
                this.OnPathChanging(value);
                this._Path = value;
                this.OnPathChanged();
                this.OnPropertyChanged("Path");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Path;
        partial void OnPathChanging(string value);
        partial void OnPathChanged();
        /// <summary>
        /// There are no comments for Property BrowserName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BrowserName")]
        public string BrowserName
        {
            get
            {
                return this._BrowserName;
            }
            set
            {
                this.OnBrowserNameChanging(value);
                this._BrowserName = value;
                this.OnBrowserNameChanged();
                this.OnPropertyChanged("BrowserName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _BrowserName;
        partial void OnBrowserNameChanging(string value);
        partial void OnBrowserNameChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedDate")]
        public global::System.DateTimeOffset CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this._CreatedDate = value;
                this.OnCreatedDateChanged();
                this.OnPropertyChanged("CreatedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.DateTimeOffset _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTimeOffset value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedDate")]
        public global::System.DateTimeOffset ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
                this.OnPropertyChanged("ModifiedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.DateTimeOffset _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTimeOffset value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property DesktopGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DesktopGroups")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::CitrixCloudClient.Citrix.Monitor.Model.DesktopGroup> DesktopGroups
        {
            get
            {
                return this._DesktopGroups;
            }
            set
            {
                this.OnDesktopGroupsChanging(value);
                this._DesktopGroups = value;
                this.OnDesktopGroupsChanged();
                this.OnPropertyChanged("DesktopGroups");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::CitrixCloudClient.Citrix.Monitor.Model.DesktopGroup> _DesktopGroups = new global::Microsoft.OData.Client.DataServiceCollection<global::CitrixCloudClient.Citrix.Monitor.Model.DesktopGroup>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnDesktopGroupsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::CitrixCloudClient.Citrix.Monitor.Model.DesktopGroup> value);
        partial void OnDesktopGroupsChanged();
        /// <summary>
        /// There are no comments for Property ApplicationInstances in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ApplicationInstances")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::CitrixCloudClient.Citrix.Monitor.Model.ApplicationInstance> ApplicationInstances
        {
            get
            {
                return this._ApplicationInstances;
            }
            set
            {
                this.OnApplicationInstancesChanging(value);
                this._ApplicationInstances = value;
                this.OnApplicationInstancesChanged();
                this.OnPropertyChanged("ApplicationInstances");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::CitrixCloudClient.Citrix.Monitor.Model.ApplicationInstance> _ApplicationInstances = new global::Microsoft.OData.Client.DataServiceCollection<global::CitrixCloudClient.Citrix.Monitor.Model.ApplicationInstance>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnApplicationInstancesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::CitrixCloudClient.Citrix.Monitor.Model.ApplicationInstance> value);
        partial void OnApplicationInstancesChanged();
        /// <summary>
        /// There are no comments for Property ProbeRuleApplications in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ProbeRuleApplications")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::CitrixCloudClient.Citrix.Monitor.Model.ProbeRuleApplication> ProbeRuleApplications
        {
            get
            {
                return this._ProbeRuleApplications;
            }
            set
            {
                this.OnProbeRuleApplicationsChanging(value);
                this._ProbeRuleApplications = value;
                this.OnProbeRuleApplicationsChanged();
                this.OnPropertyChanged("ProbeRuleApplications");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::CitrixCloudClient.Citrix.Monitor.Model.ProbeRuleApplication> _ProbeRuleApplications = new global::Microsoft.OData.Client.DataServiceCollection<global::CitrixCloudClient.Citrix.Monitor.Model.ProbeRuleApplication>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnProbeRuleApplicationsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::CitrixCloudClient.Citrix.Monitor.Model.ProbeRuleApplication> value);
        partial void OnProbeRuleApplicationsChanged();
        /// <summary>
        /// There are no comments for Property ProbeLogs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ProbeLogs")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::CitrixCloudClient.Citrix.Monitor.Model.ProbeLog> ProbeLogs
        {
            get
            {
                return this._ProbeLogs;
            }
            set
            {
                this.OnProbeLogsChanging(value);
                this._ProbeLogs = value;
                this.OnProbeLogsChanged();
                this.OnPropertyChanged("ProbeLogs");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::CitrixCloudClient.Citrix.Monitor.Model.ProbeLog> _ProbeLogs = new global::Microsoft.OData.Client.DataServiceCollection<global::CitrixCloudClient.Citrix.Monitor.Model.ProbeLog>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnProbeLogsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::CitrixCloudClient.Citrix.Monitor.Model.ProbeLog> value);
        partial void OnProbeLogsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
        
    }
    
I'm trying to reach the "DesktopGroups"

**Comment by object** [comment]
No, this won't work. You auto-generated proxy classes so they inherit from Microsoft.OData.Client.BaseEntityType. I am not even sure these classes have default public constructors. These classes are meant to be used with Microsoft.OData.Client, it's a different client library. Define your own entity classes and they will work.

**Comment by nazyf** [comment]
Do you mean simple classes with properties? Serializeable objects?
I generated the DataServiceContext using oDataClient class

**Comment by object** [comment]
Yes. Just simple classes that the library is able to instantiate. DataServiceContext that you are using is for a different library. Simple.OData.Client has no use for such DataServiceContext, and when looking at the code you pasted I didn't even find default public constructor for proxy classes. You can't just send different types between different libraries and expect them to work.

**Comment by nazyf** [comment]
I will check it now. Thanks.

**Comment by nazyf** [comment]
It worked. Thanks :)

**Comment by nazyf** [comment]
Another question, how can I increase the query depth?
I tried:
await client.For<ApplicationInstance>().
                                                Expand(**ODataExpandOptions.ByReference(5)**, "Session/Machine, Application/DesktopGroups/Machines, Session/User").FindEntriesAsync();

also tried **ODataExpandOptions.ByValue(5)** and it doesn't work.
It throw the following error:
"The query specified in the URI is not valid. The request includes a $expand path which is too deep. The maximum depth allowed is 2. To increase the limit,
	set the 'MaxExpansionDepth' property on EnableQueryAttribute or ODataValidationSettings."

**Comment by nazyf** [comment]
Hi, do you have something about this?

**Comment by sixlettervariables** [comment]
@nazyf your OData server sets the maximum expansion depth. Not the client.
