### ISSUE TITLE
client is retrieving the whole metadata

### ISSUE THREAD

**Issue by caesar80** [simple-odata-client/Simple.OData.Client#585]
The client is retrieving the whole metadata at the first call which is too large (more than 30MB). On slow connections it is a huge problem. Is there any parameter/setting to avoid fetch metadata?

**Comment by NetTecture** [comment]
> On slow connections it is a huge problem.

Not really, unless they are really slow. Does the server not compress that properly? Metadata has 2 amazing properties:
* It is static server side (i.e. you can cache it)
* It is EXTREMELY nice to compress given that it is EXTREMELY repetitive ;)

I would not really wonder if that 30mb turn into 2-3 mb.

What you CAN do is not retrieve it. There is support for MetaDataDocument in clientsettings. So you can embed it in your application or cache it on disc.

**Comment by object** [comment]
As suggested by @NetTecture, you can place Metadata document locally and refer to it using ODataClientSettings.
