### ISSUE TITLE
Incorrect function call

### ISSUE THREAD

**Issue by haharoi** [simple-odata-client/Simple.OData.Client#594]
I have two entity sets A and B and two OData functions operating on entitysets: A.**GetDirection**() and B.**GetDirections**(), and I'm utilizing the instance of Simple.OData.Client with BestMatchResolver.
And it turns out that I cannot call **GetDirections**() on B entity set; instead, the constructed URL calls B.GetDirection() (with the final -s stripped out).

I looked through the code and found out that OData function and action names are subject for matching with INameMatchResolver. So, in my case, all bound functions from the metadata are inspected and the first one which matches ("in terms of" BestMatchResolver) **GetDirections** is used in URL.

This is obviously not right. I would suggest:
1. Not to use the NameMatchResolver for function matching, or
2. Modify the Simple.OData.Client.V4.Adapter.Metadata.GetFunction(string) so that it at first looks for function exact match.

I can provide the fix for either former of latter case.

**Comment by UMFrankS** [comment]
For exact matching it is possble to set the NameMatchResolver to strict:
`settings.NameMatchResolver = ODataNameMatchResolver.Strict;
myClient = new ODataClient(settings);`

**Comment by haharoi** [comment]
I know. But I have to use BestMatchResolver because of its ability to pluralize/singularize entity set names. The problem is that in my scenario entity names have to be singularized but function/action names should not.

**Comment by haharoi** [comment]
Any news on the topic? Hasn't anyone else faced the similar issue?
