### ISSUE TITLE
Update call to CRM hangs forever

### ISSUE THREAD

**Issue by kgenov** [simple-odata-client/Simple.OData.Client#599]
Hi Vagif,

I'm currently on version 5.6.2. When I make the following call to CRM to update a record the call hangs forever:

       public override void UpdateItem(int? companyId, IDictionary<string, object> entryKey, IDictionary<string, object> record)
        {
            Task<IDictionary<string, object>> task = this.client.UpdateEntryAsync(this.serviceConfigurationParser.GetResourceName(), entryKey, record);
            
            Task.Run(() => task).Wait(); // **hangs forever**
        }

The very same code works just fine with NAV and another product called CDATA. It is just CRM when I try to update when it hangs. I know the CRM metadata is big (> 4 MB), so i put it in a local file, removed almost all the entities I do not use (which made it ~ 300 KB) without any effect. 

I monitor the calls with Fiddler and I never see an OData call going out for the update. 

So I assume the client goes in a loop internally for whatever reason? I think I can safely exclude the deadlock situation here, as in one of my other issues I posted recently,  as the same code works fine now with other ERPs. And it also works fine when reading data from CRM. I have a feeling it does not like something in the metadata, but can you give me a hint how to troubleshoot this one?

Thanks again!
Kiril

**Comment by object** [comment]
Hmm, but isnt't the same as this one?
https://github.com/simple-odata-client/Simple.OData.Client/issues/587

You are using Wait again instead of awaiting result. This is a bad practice which can lead to problems like the one you experienced. Can you change the implementation? Try using await and see what happens.

**Comment by kgenov** [comment]
Well, I do not believe it is the same one, this is why I mentioned I can exclude the deadlock situation as it works fine for other ERPs. It is just problematic with CRM calls (both onpremise and O365 actually), and it happens only when I do update/create, everything else works just fine, i still use Wait and Result in other calls with no problems at all. In #587 I was even not able to get the metadata, but now after I started using the Task.Run approach, which prevents deadlocks all started working fine, it is just the update/create with CRM that gives me troubles.

I can certainly try the await approach but at some higher level I still have to call Result or Wait, as my project is not async oriented right now. I actually tried that in #587 but it didn't help. So probably the whole stack needs to be async, which will be very time consuming to introduce in my project at this point ... Anyway, maybe I can try to create a separate simple project with only async calls to see if that will make any change and let you know.

Thanks for all your help!
Kiril

**Comment by kgenov** [comment]
Actually, another point to make - in #587 there was always an outgoing OData call, which was successful (monitored by Fiddler), but after the OData call was completed the API did not responded, obviously entering a deadlock. But now there is even no outgoing OData call. So this is why i assumed it is something different this time, maybe something with the metadata that is wrong ..

**Comment by object** [comment]
Then I would advise to extract a small project and try await approach there. Or build Simple.OData.Client from sources and debug it to see where inside the UpdateEntryAsync the deadlock occurs. Since people are successfully using the library with this scenario, there must be something related to how it is used in your code.

**Comment by kgenov** [comment]
Ok, thank you for your responses! Will try a sample project and get back to you.

**Comment by kgenov** [comment]
Hi Vagif,

I just had a real quick view of the code. I see that there is no ConfigureAwait(false) at the places I marked on the screenshot. Is that a possible reason for my issues?

![image](https://user-images.githubusercontent.com/9478248/55400545-d3c59300-5556-11e9-9886-2ed74c6072f6.png)

Thanks!
Kiril

**Comment by object** [comment]
Thank you Kiril, this the possibility of course. Do you have a chance to compile custom version of the library and test with the changes in these two places to see if it helps? If it does, send me the PR and we can release the fix asap.

**Comment by kgenov** [comment]
Ok, will try and get back to you, but I might need a day or two for that ...

**Comment by kgenov** [comment]
Hi Vagif,

here is my pull request with changes which fixed my deadlock issues - #603 .

Thanks!
Kiril

**Comment by kgenov** [comment]
Thanks, all works fine now!
