### ISSUE TITLE
Is that possible to ignore 'odata.context' in the payload when parse response to json?

### ISSUE THREAD

**Issue by gItSpLasHeR** [simple-odata-client/Simple.OData.Client#601]
In my scenario  the response only include value part in json from a GET query like below
`{
    "value": [
        {
            "ID": 1,
            "Name": "aaa"
        },
        {
            "ID": 2,
            "Name": "bbb"
        }
    ]
}`
and if i use `FindEntriesAsync` with fluentAPI,  **Simple.Odata.Client gets 'The required instance annotation odata.context was not found' exception**
similar like #598  , however i cannot do the not-require-result trick since i am a GET query.

in addition there is a work-around by using `BuildRequestFor` and parse response manually, but looks not nice. 
so i would like know is there any way to ignore 'odata.context' in the payload so response can parse to object directly?

**Comment by gItSpLasHeR** [comment]
well.  find a way attaching "odata.context" in the result by adding metadata=minimal, and now no issue occur. close this.

**Comment by songzj8** [comment]
Hi, 
I'm having the same issue.
Could you tell me how to fix the issue?
Thanks.
