### ISSUE TITLE
Can we use Simple.OData.Client where Metadata endpoint/information not available?

### ISSUE THREAD

**Issue by GSingha** [simple-odata-client/Simple.OData.Client#604]
Odata is new to me. Currently, I am trying to use Simple.OData.Client.  The API  I'm  comnsuming is build on OData but the metadata endpoint is not available. 
Now I believe without metadata information/endpoint OData client will not going to work but Iam not sure.

So, is it possible to use Simple.OData.Client where metadata URL not being exposed by API or metadata information not available?

**Comment by phatcher** [comment]
You should be able to download the metadata from somewhere, it's not really an OData endpoint without metadata,; you can then assign it statically in your client.

**Comment by GSingha** [comment]
@phatcher  thank you.
