### ISSUE TITLE
[Question] How to parse 'api-version' (parameter) using Simple.OData.V4.Client

### ISSUE THREAD

**Issue by okkaido** [simple-odata-client/Simple.OData.Client#611]
Hi,

i have a OData Controller (V4) and API-Versioning is activated.

Now i am writing the Client using Simple.OData.V4Client:
`
var client = new ODataClient("http://localhost:58015/api");
var response = await client.FindEntriesAsync("MyEndpoint?api-version=1.0&%24select=Name");
`

The api-version is defined as parameter in the URL.
Now, i want to use the Fluent API syntax like:
`var response = await client.For("MyEndpoint").Select("Name").FindEntriesAsync();`

But were can i parse the "api-version"?

Best regards,
Tobi

**Comment by object** [comment]
You use QueryOptions:

1. Define a class that represents your query options, e.g.:

```
    public class QueryOptions
    {
        public int IntOption { get; set; }
        public string StringOption { get; set; }
    }

```

2. Add QueryOptions clause, like this:

```
    _client
    .For<Product>()
    .Filter(x => x.ProductName == "abc")
    .QueryOptions<QueryOptions>(y => y.IntOption == 42 && y.StringOption == "xyz")
    ...

```

This should do the trick.

**Comment by okkaido** [comment]
Thank you!
