### ISSUE TITLE
EDM.Byte with Precision fails

### ISSUE THREAD

**Issue by pstemper** [simple-odata-client/Simple.OData.Client#615]
The Metadata for a field of type EDM.Byte has a Precision specified.  When Simple.OData.Client loads the Metadata XML, it errors with:
'Unable to load OData adapter from assembly Simple.OData.Client.V4.Adapter'
EdmParseException: Encountered the following errors when parsing the EDMX document: 
UnexpectedXmlAttribute : The attribute 'Precision' was not expected in the given context. : (38, 56)

Line 38 in the Metadata is:
        Property Name="BFull" Type="Edm.Byte" Precision="3"

If I modify the metadata and remove the "Precision="3"" and then manually load the metadata, the parsing works correctly.

According to the MS CSDL definition, I believe Precision should be supported on an Edm.Byte type:  https://msdn.microsoft.com/en-us/data/bb399548%28v=vs.85%29?f=255&MSPPError=-2147217396

I would prefer to not have to download the metadata, modify it, and then load it manually.  If nothing else, is there a way to get the parser to ignore unexpected tags like Precision on and Edm.Byte type?

Paul

**Comment by object** [comment]
The library relies on Microsoft's Microsoft.OData.Core and Microsoft.OData.Edm to parse metadata file. So if those libs fail to parse metadata, there's nothing Simple.OData.Client can do about it. But as a workaround, you can save modified metadata file locally and point to it in ODataClientSettings, it has a property MetadataDocument that can you can assign a string with the metadata content, so it won't attempt to read service metadata.

**Comment by pstemper** [comment]
That is what I figured I would have to do.  In fact, I already have done that and it is working.  I was just hoping their might be another work-around.  I know they have a flag to ignore unexpected attributes (IgnoreUnexpectedElementsAndAttributes), so I thought maybe there was a place to "pass-that-through" to their functions.

Thanks for the wonderful library and the support!!!

Paul
