### ISSUE TITLE
Better support for derived types

### ISSUE THREAD

**Issue by hvaring** [simple-odata-client/Simple.OData.Client#622]
Hi,

I've ran into some issues when it comes to OData services which have a complex type inheritance. I know there are some open issues for this already (#158, #575, #302, #306), so I will try to summarize my issues here:
- Converters are required for converting abstract classes to their derived type. This in itself can be worked around by creating a converter (like in #158). It is beneficial to use the `ToObject` extension method from `DictionaryExtensions` (it handles navigation properties), but it is marked as internal. This means custom converters have to copy `DictionaryExtensions` with all its dependencies to use that method. Perhaps a solution could be implemented where we can register mappings between type annotations to CLR types, and let the framework handle the conversion?
- Annotations are missing from collections of navigation properties, which means the converter approach above wouldn't work. I created PR #621 to address this.
- Support is missing for casting a type within a filter:
```csharp
public abstract class Animal { }

public class Dog : Animal
{
    public string Breed { get; set; }
}

public class Cat : Animal
{
    public string Name { get; set; }
}
```

With the above structure, it is legal in OData to create a query `animals?$filter=(isof('Dog') and Dog/Breed eq 'Poodle') or (isof('Cat') and Cat/Name eq 'Pinky')`. It would be nice to be able to write something like:
```csharp
var animals = await client.For<Animal>().Filter(x => (x is Dog && ((Dog)x).Breed == "Poodle") || (x is Cat && ((Cat)x).Name == "Pinky")).FindEntriesAsync();
```
or
```csharp
var animals = await client.For<Animal>().Filter(x => (x is Dog && (x as Dog).Breed == "Poodle") || (x is Cat && (x as Cat).Name == "Pinky")).FindEntriesAsync();
```

**Comment by phatcher** [comment]
@hvaring I think I have a general solution to the subtyping problem; basically we look at the type annotation to determine which subclass to populate and then call ToObject with the correct type.  This was what all the TypeCache etc stuff was working towards.

I'll put my current code on a branch this weekend and you can take a look to see what you think

**Comment by hvaring** [comment]
Hi @phatcher, I would be interested in testing that out. Do you have a branch available?

**Comment by phatcher** [comment]
@hvaring I should have something this weekend, day job very busy at the moment.

**Comment by phatcher** [comment]
@hvaring There's a new branch on my fork [features/575_SubTypes](https://github.com/phatcher/Simple.OData.Client/tree/features/575_SubTypes).

It's complete and there are only a few minor issues that need resolving/noting; 

1. You have use the TypeCache.Register method if you have dynamic properties.
2. We use a different INameResolver than the one in TypeCache, could expose it but wasn't sure
3. We only populate the base type if we have a subtype that we don't recognise

Let me know how you get on.  I'll do some more extensive testing against my main project next week as well.

**Comment by hvaring** [comment]
@phatcher, I tested out the changes and it solves the subtyping problem for my use case (no dynamic properties). It worked out of the box when using annotations.

**Comment by weitzhandler** [comment]
In my scenario I have a base `Contact` and `Person` and `Company` subclasses.

[Here](https://gist.github.com/weitzhandler/a0bc84d715d16dfd2035abcf654d07c2#file-metadata-xml)'s the metadata from server, and here's the JSON received from the server:

```json
{
  "@odata.context": "https://test.myproject.com/api/$metadata#Contacts",
  "value": [
    {
      "@odata.type": "#MyProject.Data.Person",
      "Id": 1,
      "DisplayName": "Paul Hatcher",
      "FirstName": "Paul",
      "LastName": "Hatcher"
    },
    {
      "@odata.type": "#MyProject.Data.Person",
      "Id": 2,
      "DisplayName": "Vagif Abilov",
      "FirstName": "Vagif",
      "LastName": "Abilov"
    }
  ]
}
```

When I call oClient.For<Contact>().FindEntriesAsync().ToList()`, I get the following exception:

>Simple.OData.Client.Extensions.ConstructorNotFoundException: 'Could not find a constructor for type 'Contact' with the following argument types: '

StackTrace:

>   at Simple.OData.Client.Extensions.ExpressionActivator.CreateActivator(Type type, Type[] parameters)
   at Simple.OData.Client.Extensions.ExpressionActivator.CreateActivator(Type type)
   at Simple.OData.Client.Extensions.DictionaryExtensions.<>c.<CreateInstance>b__17_0(Type t)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Simple.OData.Client.Extensions.DictionaryExtensions.CreateInstance(Type type)
   at Simple.OData.Client.Extensions.DictionaryExtensions.ToObject(IDictionary`2 source, ITypeCache typeCache, Type type, Boolean dynamicObject)
   at Simple.OData.Client.Extensions.DictionaryExtensions.ToObject[T](IDictionary`2 source, ITypeCache typeCache, Boolean dynamicObject)
   at Simple.OData.Client.FluentClientBase`2.ConvertResult(IDictionary`2 result, String dynamicPropertiesContainerName)
   at Simple.OData.Client.FluentClientBase`2.<>c__DisplayClass91_0.<FilterAndTypeColumnsAsync>b__0(IDictionary`2 z)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.ObjectModel.ObservableRangeCollection`1.ContainsAny(IEnumerable`1 collection) in D:\Users\Shimmy\Documents\Visual Studio 2019\Projects\MyProject\MyProject.Client.ViewModels\Services\ObservableRangeCollection.cs:line 574

The question is why is it trying to instantiate a `Contact` when it's clear in the JSON that the type is a `Person`?

**Comment by weitzhandler** [comment]
What else does it take to get that branch merged?

**Comment by weitzhandler** [comment]
What else does it take to get that branch merged?
I'm willing to contribute.

**Comment by weitzhandler** [comment]
> @phatcher 
> There's a new branch on my fork [features/575_SubTypes](https://github.com/phatcher/Simple.OData.Client/tree/features/575_SubTypes). 
> It's complete and there are only a few minor issues that need resolving/noting;

What else does it take to get that branch merged? I'm willing to contribute.

**Comment by weitzhandler** [comment]
Really it should attempt to resolve type according to the type gathered from JSON and metadata.

**Comment by Ricciolo** [comment]
Hi folks, any news about this fork. Polymorphism is an important feature

**Comment by phatcher** [comment]
I rebased my changes and they all still work, will issue a pull request

**Comment by weitzhandler** [comment]
Thank you Paul!

**Comment by manureini** [comment]
Hello ;)
@phatcher Are there any news about your pr?

**Comment by manureini** [comment]
`IncludeAnnotationsInResults = true` in ODataClientSettings is required to get the support for derived types
