### ISSUE TITLE
Use raw $expand value in simple odata client

### ISSUE THREAD

**Issue by ysmoradi** [simple-odata-client/Simple.OData.Client#623]
I've following $expand raw value which is working when I test it using swagger.

```?$expand=Products($expand=*)```

How can I use it in Simple OData Client. I'm receiving following exception:

```
Simple.OData.Client.UnresolvableObjectException: 'Association [Products($expand=*)] not found'
```

**Comment by object** [comment]
The wild card specifier it not currently supported.
