### ISSUE TITLE
JsonProperty/Ignore support

### ISSUE THREAD

**Issue by phatcher** [simple-odata-client/Simple.OData.Client#627]
Typically your client model is marked up with Json serialization properties, but currently SoC only supports DataMember/NotMapped, forcing you potentially to mark up twice.

As we reference the attribute names via strings, we can easily add support for JsonProperty and JsonIgnore without affecting the binary dependencies of the package.

**Comment by object** [comment]
Agree, good suggestion.

**Comment by phatcher** [comment]
@object, It's on my development branch, I just need to change the tests as my changes break some of the Ship integration tests, but it works nicely.

**Comment by object** [comment]
Oops, I just committed the change myself. But feel free to review and update.
