### ISSUE TITLE
Filter not working when passing expand entity property

### ISSUE THREAD

**Issue by chigivigi** [simple-odata-client/Simple.OData.Client#639]
When running a query that contains filter with a link entity property it returns an error message:

Microsoft.OData.ODataException: 'The type 'WebAppOdata.Account' is not supported when converting to a URI literal.'

The code looks like this:

            // get service
            IEnumerable<Billing_Service> billingserviceForSubscription = await odataClient.For<Billing_Service>()
                .Select(x => new { x.Id, x.Name, x.Account }).Expand(x => new { x.Account }).Select(x => new { x.Account.Id, x.Account.Name }).FindEntriesAsync();
            // get current account
            Account current_account = billingserviceForSubscription.First().Account;
            // get current service
            Billing_Service current_billing_serice = billingserviceForSubscription.First();

            Guid accID = current_account.Id;
            Guid billServiceID = current_billing_serice.Id;

            // get subscriptions
            var subscriptions = await odataClient.For<Suscription>()
                .Expand(x => x.Account).Expand(x => x.Billing_Service)
                .Filter(x => x.Account.Id == ((Guid)current_account.Id) && x.Billing_Service.Id == billServiceID).GetCommandTextAsync();

The Billing Service, Subscription and Account are CRM entities.

The definition of the Entities look like this:

    public class Account
    {
        [Extensions.Column(Name = "xxxxx")]
        public Guid Id { get; set; }
        [Extensions.Column(Name = "name")]
        public string Name { get; set; }
    }

    [Table("xxxxxxx")]
    public class Billing_Service
    {
        [Extensions.Column(Name= "xxxxx")]
        public Account Account { get; set; }

        [Extensions.Column(Name = "xxxxx")]
        public Billing_Period_Type Billing_Period_Type { get; set; }

        [Extensions.Column(Name = "xxxxx")]
        public Guid Id { get; set; }

        [Extensions.Column(Name= "statuscode")]
        public string StatusCode { get; set; }
        [Extensions.Column(Name= "xxxxx")]
        public string Name { get; set; }

        [Extensions.NotMapped]
        public BillingEnabled BillingEnabled { get; set; }

        [Extensions.Column(Name = "xxxxx")]
        public long BillingEnabledOS
        {
            get
            {
                return (long)BillingEnabled;
            }
            set
            {
                BillingEnabled = (BillingEnabled)value;
            }
        }
    }
    [Table("xxxxx")]
    public class Suscription
    {
        [Extensions.Column(Name= "xxxxx")]
        public Guid Id { get; set; }
        [Extensions.Column(Name= "xxxxx")]
        public string Name { get; set; }
        [Extensions.Column(Name= "xxxxx")]
        public Account Account { get; set; }
        [Extensions.Column(Name= "xxxxx")]
        public Billing_Service Billing_Service { get; set; }
    }

    [Serializable]
    public enum BillingEnabled
    {
        Yes = 400_000_001,
        No = 400_000_000
    }

When you pass a hard coded variable in the query filter it works.

            // get subscriptions
            var subscriptions = await odataClient.For<Suscription>()
                .Expand(x => x.Account).Expand(x => x.Billing_Service)
                .Filter(x => x.Account.Id == accID && x.Billing_Service.Id == billServiceID).GetCommandTextAsync();

I also tried to run the query with another class that has same properties but does NOT have map attributes and that also works with filter.

            Account2 acc2 = current_account;

            var subscriptions = await odataClient.For<Suscription>()
                .Expand(x => x.Account).Expand(x => x.Billing_Service)
                .Filter(x => x.Account.Id == acc2.Id && x.Billing_Service.Id == billServiceID).GetCommandTextAsync();

The class looks like this:

    public class Account2
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
    }

**Comment by mangzee** [comment]
I have the same issue as that of @chigivigi .
