### ISSUE TITLE
question: routing when calling For

### ISSUE THREAD

**Issue by weitzhandler** [simple-odata-client/Simple.OData.Client#642]
Hi,

First of all I'd like to thank you for the great work on this awesome library ❤

I'm new to OData, and I'm setting up the server side as explained in [this](https://devblogs.microsoft.com/odata/supercharging-asp-net-core-api-with-odata/) article, which means I decorate the action with `[EnableQuery]` and the controller with `[Route("api/[controller]")]`.

My question is if in the client side, I can automate the route, so that if I provide `mywebsite.com/api` and I go `oDataClient.For<Contact>()`, it'll add `contacts` path to the URL.

Is there a way to intercept the `For` method to 'inject' a route into the URL?
Any other ways?

BTW, the `ODataClient` is registered by the DI container as explained [here](https://github.com/simple-odata-client/Simple.OData.Client/issues/416#issuecomment-436334552).

**Comment by object** [comment]
By injecting a route do you mean customizing its name? If so, you can do this by providing the actual resource name in For method, e.g. For("my-contacts").

Hope this helps.

**Comment by weitzhandler** [comment]
I prefer it be inferred automatically by the pluralizer and attached to the query URL.

**Comment by object** [comment]
Pluralizer also does it for you. In the case you described above it will work, because "contacts" is a pluralised from of "contact".

**Comment by weitzhandler** [comment]
Can you please refer me to the "attributes" docs.
Where is the code that the Uri gets assigned to?

Is it over here?

https://github.com/simple-odata-client/Simple.OData.Client/blob/8c2807fa3632084f07dc83f7900ae8ccc96ddc0b/src/Simple.OData.Client.Core/ODataRequest.cs#L67-L70

I tried tampering with the Uri at the `ODataClientSettings.BeforeRequest`, but it already gets there when the Url and the annotations are all set.
It looks like this: `https://www.mysite.com/api/$annotations`) whereas I want to inject `contacts` path to it, so it looks like the following: `https://www.mysite.com/api/contacts/$annotations`

**Comment by weitzhandler** [comment]
The thing is that really it isn't the `HttpClient.BaseAddress` job to take care of routes, it's really the `HttpRequestMessage.RequestUri`, so I'm looking for a bleeding edge that I can set the route according to the requested entity type.

Here's how I tried to do this:

//service config
static void ConfigureHttpClients(IServiceCollection services)
{
  services.AddSingleton(Pluralizers.Cached); // and some others

  services
    .AddHttpClient<ApiClient>()
    .ConfigurePrimaryHttpMessageHandler(sp => sp.GetRequiredService<IgnoreCertificateHandler>())
    .ConfigureHttpClient<ApiBaseAddressConfigurator>()
    .ConfigureHttpClient<TokenConfigurator>();

  services.AddSingleton(sp =>
  {
    var factory = sp.GetRequiredService<IHttpClientFactory>();
    var client = factory.CreateClient<ApiClient>(); //my custom ex. method to create HttpClient itself
    return new ODataClientSettings(client)
    {
      IncludeAnnotationsInResults = true
    };
  });

  /**** some other cr@p ****/

  services.AddTransient(typeof(IODataClient<>), typeof(ODataClient<>));
}
```

Then

```c#
public interface IODataClient<TEntity> : IODataClient
{
}

public class ODataClient<TEntity> : ODataClient, IODataClient<TEntity>
{
  const char Delimiter = '/';
  public ODataClient(ODataClientSettings settings, IPluralizer pluralizer) : base(settings)
  {
    settings.BeforeRequest = req =>
    {
      var typeName = typeof(TEntity).Name;
      var plural = pluralizer.Pluralize(typeName);
      var client = settings.HttpClient;
      var builder = new UriBuilder(client.BaseAddress);

      /* ↓↓↓↓↓↓↓↓ */    
      builder.Path = $"{builder.Path.Trim(Delimiter)}{Delimiter}{plural.ToLowerInvariant()}";
      // how do I efficiently 'inject' the route (i.e. /contacts after the base Uri, but before the OData annotations in a reliable manner
      req.RequestUri = builder.Uri;
      /* ↑↑↑↑↑↑↑↑ */

    };
  }
}
```

**Comment by object** [comment]
For resource/collection it's DataContract and Table attributes that are recognized.
For columns/fields it's Data, DataMember, Column, JsonProperty. In addition NotMapped and JsonIgnore are supported.

Not sure if this is explained in Wiki, PRs are welcome :-)

**Comment by weitzhandler** [comment]
On the client side entities?

**Comment by object** [comment]
Simple.OData.Client _is_ about client side, it has nothing to do with the server side. And I believe you are overcomplicating the matter. Check out the unit tests, integration tests, there are plenty of examples of how to map C# entity type to OData resource type without intercepting anything.

**Comment by weitzhandler** [comment]
Would you consider a PR adding a new property on `ODataClientSettings` called `InferRoutNameFromCollectionType : bool` etc, that when set to true, modifies the `HttpRequestMessage.RequestUri` to include that?

**Comment by weitzhandler** [comment]
OK, lemme close this issue for now just to keep the table clean, should I encounter any problems and I'll come back then.
Thank you!

**Comment by weitzhandler** [comment]
I had to make sure the edm is configured properly on the server. Now that the annotations are coming through it's all working fine.
Thank you!
