### ISSUE TITLE
QueryOptions ignored when requesting Media Entities

### ISSUE THREAD

**Issue by SiberaIndustries** [simple-odata-client/Simple.OData.Client#645]
Hi,

this issue relates to #499. We are working with OData v4 and versioned APIs. So we have to respect the different data contracts. Let's say in Version 1.0 of API X was a string property `Name` in `SomeMediaEntity` defined, which was removed in version 1.1. As the regular json outcome changes, the resulting raw value should also be changed. For that, we want to identify the requested API version with an `api-version` query parameter and everything is working well except for the raw value requests. Given the following example:

```cs
var resultStream = await Client
    .For<SomeMediaEntity>()
    .Key(42)
    .QueryOptions(new Dictionary<string, object> { { "api-version", "1.1" } })
    .Media()
    .GetStreamAsync();
```

I would expect this request:  
`GET <url><port>/SomeMediaEntities/$value?api-version=1.1 application/octet`  
But the result is:  
`GET <url><port>/SomeMediaEntities/$value application/octet`

I can't find any rule in the OData specs which would disallow the use of query parameters in this kind of requests. Is this in addition of #499 possible to integrate?

**Comment by billnguyense** [comment]
I am getting the same issue with `FindEntryAsync()`

```csharp
await ODataClient.For<MyEntityObject>()
     .Filter(x => (x.Id == 123 || x.Id == "-1"))
     .Expand(x => x.ChildObject.Select(y => y.GrandChildObject))
     .QueryOptions(new Dictionary<string, object> { { "api-version", "1.1" } })
     .FindEntryAsync();
```
