### ISSUE TITLE
NavigationTo Insert/Update fails

### ISSUE THREAD

**Issue by chigivigi** [simple-odata-client/Simple.OData.Client#648]
I am working on Microsoft Dynamics 365 Business Central.
For my get actions I am using the navigationTo method because all other entities are based on company entity and if I directly put the company and it's id inside the base uri Odata Client component the endpoint will no longer be able to reference the entities.

I would create a navigation property inside my c# company model and use it to call the other entity while still using the root Business Central endpoint. (https://api.businesscentral.dynamics.com/v1.0/{tenantId}/sandbox/api/v1.0/)

I tried using the insert and update action in the same fashion but then I get the error that the entity type is not found:
Simple.OData.Client.UnresolvableObjectException: 'Entity type [companies(companyGuid)/customers] not found.

My c# code looks like this:
`var newCustomer = await odataClient.For<Company>().Key(companyId).NavigateTo(x => x.Customer).Set(new { DisplayName = "Test Customer 1", Email = "tc1@test.com", Address = new { City = "City1", PostalCode = "12200" } }).InsertEntryAsync();`

Seems like navigation property and function can't be used for Insert/Update (haven't tried Delete), while the Get works fine:
`var customers = await odataClient.For<Company>().Key(companyId).NavigateTo(x => x.Customer).FindEntriesAsync();`

I need to Create/Update this way because the Customer Entity is not available from root (as all the other entities too, except for Company) because Business Central API works like this: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/walkthrough-creating-and-interacting-odata-v4-bound-action

**Comment by tomidix** [comment]
@object 
I'm having the same issue as @chigivigi .

InsertEntryAsync() invokes error which he mentioned, however the record is created in Business central successfully.
By adding dlls with pdbs I've managed to track the issue.
It's in Metadata.cs, ln362
`entityType = GetEntityTypes().SingleOrDefault(x => x.Name == collection.Name);`

_collectionName = "companies(guid)/customers"
GetEntityTypes() contains record with FullName="Microsoft.NAV.customer" and Name = "customer"_

When you look at ln362 it's clear why entityType is null;
x.Name = "customer" and collection.Name = "customers" for the record which should match.

Hopefully this is enough info for you to make a fix for this as you know better how it works with pluralizer. 

Update works fine to me, without errors. Delete too.
