### ISSUE TITLE
Expand wildcard *

### ISSUE THREAD

**Issue by gem81** [simple-odata-client/Simple.OData.Client#649]
http://server/db/odata/standard.odata/Catalog_Organizations?$expand=DefaultBankAccount/*

```csharp
                var orgList = await client
                    .For<Catalog_Organizations>()
                    .Expand("DefaultBankAccount/*")
                    .FindEntriesAsync();
```

and we are getting 
```{"Navigation property [*] not found"}```

**Comment by Discjoggy** [comment]
Is it allowed to use wildcards in `$expand` expressions? Couldn't find any information about that in the specs.

**Comment by lordmampf** [comment]
http://docs.oasis-open.org/odata/odata/v4.01/csprd05/part2-url-conventions/odata-v4.01-csprd05-part2-url-conventions.html#sec_SystemQueryOptionexpand

> a star (*) to expand all navigation properties of the identified structured instance
