### ISSUE TITLE
Count is not translated well

### ISSUE THREAD

**Issue by Echarnus** [simple-odata-client/Simple.OData.Client#677]
When I am using the .Count Fluent API function, my url is translated as _https//somedomain.com/odata/myType/$count_ instead of _https//somedomain.com/odata/myType/?count=true_. 

The API I am sending requests to is made in ASP.Net Core. Is it perhaps possible there are different implementations of OData, all though I thought it was a standard? 

I am using version 5.9.0. 

Edit: Same problem in 5.9.1.

**Comment by SiberaIndustries** [comment]
OData provides two different ways of using `$count`. Just check these two working examples:

1. https://services.odata.org/V4/Northwind/Northwind.svc/Products?$count=true
1. https://services.odata.org/V4/Northwind/Northwind.svc/Products/$count

The first returns all products in the `value` element of the JSON response and additionally it includes a `@odata.count` element, which represents the count of all products, no matter what filter you use.

The second returns the exact same count value, but it only returns the value as the raw response without any OData JSON result around.

You can find some `Simple.Odata.Client` examples at the end of the documentation:

- https://github.com/simple-odata-client/Simple.OData.Client/wiki/Retrieving-data-matching-search-criteria

**Comment by SiberaIndustries** [comment]
@Echarnus could you solve your issue?

**Comment by Echarnus** [comment]
Done. Apparently there is a bug in .Net Core about this, or at least more people have the same problem: https://github.com/OData/WebApi/issues/1153.
