### ISSUE TITLE
How to implement $filter=Name in ('name1','name2')

### ISSUE THREAD

**Issue by AmirImam** [simple-odata-client/Simple.OData.Client#684]
Hi
I can make a query that filters the data where in collection like that
http:url/Obj/$filter=Name in ('name1','name2')
how to implement it by Simple.OData.Client

**Comment by AmirImam** [comment]
Any ideas ?!

**Comment by AmirImam** [comment]
I need some help here

**Comment by UmairB** [comment]
I used `QueryOptions` fluent method to simply define my own `$filter`:
```
.QueryOptions($"$filter=Name in ({string.Join(",", names)}))")
```
Not ideal but looks like there is not support for `in` just yet

**Comment by SiberaIndustries** [comment]
This is how I deal with the missing support:

```cs
.Filter($"Name in ('{string.Join("','", names)}')")
```

**Comment by AmirImam** [comment]
So you mean there is no way to use LINQ expression with it ?

**Comment by SiberaIndustries** [comment]
Well this should work I guess, but `in` with linq is currently not supported.

```cs
.Filter(x => x.Name == "name1" || x.Name == "name2")
```
