### ISSUE TITLE
Simple.Odata Client V3 throws Exception after upgrading from VS 2017 to VS 2019

### ISSUE THREAD

**Issue by pluggy** [simple-odata-client/Simple.OData.Client#691]
Hello Vagif,

I am working on a fairly large legacy Android / iOS App with PCL-based shared libraries and Simple.Odata Client V3 4.2.9. I'm having problems updating from Visual Studio 2017 to Visual Studio 2019:

Everything works fine when compiling the Solution with VS 2017 15.9.3, but when I try compiling the same source code in debug mode with VS 2019 16.3.10, Simple.Odata.Client starts throwing an exception when reading data from the server side. 

The following exception is thrown: 
**Microsoft.Data.OData.ODataContentTypeException:** 'A supported MIME type could not be found that matches the content type of the response. None of the supported type(s) 'application/atom+xml;type=entry, application/atom+xml, application/json;odata=verbose, application/json' matches the content type 'application/xml; charset=utf-8'.'

Other than the exception thrown by Simple.Odata.Client, the app still runs fine. Also, the iOS build still works fine after updating Visual Studio. 

I'm not sure how to proceed from here. I have considered upgrading from Simple.Odata Client V3 4.2.9 to the latest version, but that would quite a bit effort since all of my shared libraries are using PCL and are not compatible NetStandard. I will do it eventually, but would prefer not to do it now if possible. 

Do you have any idea how proceed? 

Thanks,

Adrian

**Comment by object** [comment]
Version 4.x is quite old and no longer maintained. You should consider upgrading to version 5 of the library.
