### ISSUE TITLE
Select based on Model

### ISSUE THREAD

**Issue by jamierytlewski** [simple-odata-client/Simple.OData.Client#695]
Let's say I have code that looks like 

`var contactsFilter = client.For<Contact>()
                .Filter(x => x.CIF.StartsWith("473"))`

And when I'm looking at the `BuildReqeustFor` I want it to also do a `$select=` based only the fields from the model. So in the model if I only have FirstName, LastName for `Contact`, is there an easy way to have it create the URL with the `$select=FirstName,LastName` instead of returning all the values without having to use `.Select(x=>new {x.FirstName, x.LastName})`

Thanks,

Jamie

**Comment by ericcanadas** [comment]
I have the same question !!
@jamierytlewski Did you find a solution?
@object Do you have any idea how we can achieve this?

**Comment by jamierytlewski** [comment]
@ericcanadas I never found a solution except to do the `.Select(x=> new {x.})`
