### ISSUE TITLE
Provide mechanism to refresh MetadataCache

### ISSUE THREAD

**Issue by vesko-k** [simple-odata-client/Simple.OData.Client#742]
I'm using `Simple.OData.Client` in an `ASP .NET Core` site. Everything works well, but the `OData` server changes it's metadata, as provided collections for example. Unfortunately the `MetadataCache` is static and isnt refreshed until app pool is recycled. I suggest to provide a possibility to force metadata cache reload for particular address. For example via `ODataClientSettings` to trigger reload or via `ODataClient` ctor.

**Comment by watfordgnf** [comment]
We have an internal method which does this that could be exposed on the `IODataClient` interface. Would a per client refresh work?

**Comment by vesko-k** [comment]
Yes, sure.

**Comment by watfordgnf** [comment]
If it is acceptable to clear the cache for everything, you can use the static `ODataClient.ClearMetadataCache()` method.

**Comment by vesko-k** [comment]
Yes, thank you.

**Comment by phatcher** [comment]
Let us know if you have any issues as there's a note in the code regarding whether we should also clear the associated ITypeCache, if the underlying model has changed this might now contain out of date information.
