### ISSUE TITLE
Compound primary key not accepted in method signature

### ISSUE THREAD

**Issue by lanea07** [simple-odata-client/Simple.OData.Client#744]
I have an async call to the UpdateEntryAsync method which involves a table in database with a compound primary key (two fields). When using this method, as far as I've seen, it is mandatory to relate the key to that table, but when I include the object, the controller of the web service responds that the parameter dictionary contains a NULL value for the second parameter passed. Is there any solution for this or any idea how to get around it. This is my method call:

`var result = await clienteHTTP.For("tblCustomerPreferences").Key(new { customer_id = key["userID"], preference_id = 9 }).Set(registry).UpdateEntryAsync();`

The original method signatures for PUT and PATCH

`public async Task<IHttpActionResult> Put([FromODataUri] int key, Delta<tblCustomerPreferences> patch)`

`public async Task<IHttpActionResult> Patch([FromODataUri] int key, Delta<tblCustomerPreferences> patch)`

**Comment by rafek1241** [comment]
Additionally there is already support for compound keys and its covered by the tests (https://github.com/simple-odata-client/Simple.OData.Client/blob/d9fec910cb720ea0767911021e9275eacaae7ea4/src/Simple.OData.Client.UnitTests/Core/DynamicFilterAsKeyTests.cs#L120).
