### ISSUE TITLE
Support System.Text.Json 5.0.0

### ISSUE THREAD

**Issue by j2ghz** [simple-odata-client/Simple.OData.Client#769]
The dependency bound on `Simple.OData.Client` is `System.Text.Json (>= 4.7.1 && < 5.0.0)`, which prevents usage of `System.Text.Json 5.0.0`

**Comment by Jacko1394** [comment]
this issue is effecting me also, cannot use anymore with net5.0

should be easy fix as works no probs with 5.0.0-rc2

**Comment by object** [comment]
I just pushed the package 5.15.0 that is updated to use System.Text.Json 5.0.0

**Comment by ysmoradi** [comment]
Please do the same again. This time for system.text.json v6 @object

**Comment by mbauerdev** [comment]
@ysmoradi Why not contribute this feature by yourself?

**Comment by ysmoradi** [comment]
I've contributed to this repo several times by posting new issues and submitting PRs

But why I'm not contributing to this feature? Because even if I submit a PR, @object should / can release the official nuget package. The underlying change is not something special really.
