### ISSUE TITLE
Wrong Microsoft.OData.Core version in 5.22.0

### ISSUE THREAD

**Issue by zivillian** [simple-odata-client/Simple.OData.Client#815]
Version 5.22.0 from nuget results in 

```
FileNotFoundException: Could not load file or assembly 'Microsoft.OData.Core, Version=7.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```

The assembly `Simple.OData.Client.Core` references `Microsoft.OData.Core` in Version 7.9.0.0 but the nuspec states `>= 7.8.3 && < 8.0.0`, so 7.8.3 is installed automatically.

**Comment by object** [comment]
That was my mistake in version spec. Unfortunately I am on vacation and won't be able to fix it within a couple of weeks

**Comment by nsarris** [comment]
Please bare in mind there is a bug in 7.9.0 that signifanclty impacts performance in large models. I have commited a PR but it's still under review. I would suggest to fallback to 7.8.3 till it's fixed.

**Comment by object** [comment]
Thanks, that's good to know.

**Comment by object** [comment]
@nsarris I just pushed the package with updated dependencies (updated to 7.9.0) and only then realized that you commented on performance of this version. It's kind of too late to rollback. Let's see how it goes. If performance is not bearable and the review takes long time we may rollback to 7.8.3 Let's hope however that Microsoft will soon accept your PR.
