### ISSUE TITLE
Edm.Date conversion broken in 5.24 by commit 56477ea

### ISSUE THREAD

**Issue by pkanavos** [simple-odata-client/Simple.OData.Client#826]
Commit  #56477ea removed the lines that convert Edm.Date values to DateTime at https://github.com/simple-odata-client/Simple.OData.Client/blob/458fbea59e1eab15e770a5b61425f32533a81a45/src/Simple.OData.Client.Core/Cache/TypeCache.cs#L261

This causes a type conversion now.  The missing lines are

                else if ((targetType == typeof(DateTime) || targetType == typeof(DateTime?)) && value is Microsoft.OData.Edm.Date date)
                {
                    result = new DateTime(date.Year, date.Month, date.Day);
                }

The error occurs only in version 5.24 of the NuGet package. 5.22.2 works fine

**Comment by mcattle** [comment]
I can confirm that this is broken in 5.23 of the NuGet package as well.  Being able to convert a Microsoft.OData.Edm.Date to a DateTime (with nullable support) out of the box is essential for an OData client.  In the meanwhile, reverting to 5.22.2 (and remembering not to auto-upgrade the package) is an unsatisfactory workaround.

**Comment by mcattle** [comment]
I've created #828 to add the functionality back in (via implicit conversion) without re-adding the Microsoft.OData library dependency, including unit tests.

**Comment by mcattle** [comment]
> The fix by @mcattle has been merged and the issue should be fixed since release 5.25. @pkanavos could you please confirm and close the issue if it's ok now?

If I'm not mistaken, the fix was merged after the 5.25 tag was added, so will need a 5.26 release.

**Comment by Avinch** [comment]
Is there any ETA on a release with this fix being published?
