### ISSUE TITLE
Asking for bad System.Text.Json version (for .NET Core 6.0)

### ISSUE THREAD

**Issue by NetTecture** [simple-odata-client/Simple.OData.Client#836]
Simple.Odata.V4.Client is referencing System.Text.Json, with a limitation (netstandard Version 2.0) to< 6.0.0

This is not compatible with Net Core 6.0, more exact Visual Studio 2022.

I have tests using this to test an Odata server.

I get the following error:

Tests.OpenDataCore.Server to resolve this issue. 
 Tests.OpenDataCore.Server -> Microsoft.AspNetCore.Mvc.Testing 6.0.0 -> Microsoft.Extensions.Hosting 6.0.0 -> Microsoft.Extensions.Logging.EventSource 6.0.0 -> System.Text.Json (>= 6.0.0) 
 Tests.OpenDataCore.Server -> Simple.OData.V4.Client 5.25.0 -> System.Text.Json (>= 5.0.2 && < 6.0.0).	Tests.OpenDataCore.Server	C:\Work\CoreLibraries\OpenDataCore\Source\Tests.OpenDataCore.Server\Tests.OpenDataCore.Server.csproj	1	

Please issue a version targeting the net60 framework (as it seems netstandard is going away) that references the current framework.

**Comment by robertmclaws** [comment]
I have a pull request (#833) to fix this.

**Comment by davidnmbond** [comment]
While we wait, and for those that desperately need it, check out the PanoramicData fork:

- https://www.nuget.org/packages?q=PanoramicData.OData
- https://github.com/panoramicdata/PanoramicData.OData.Client

**Comment by robertmclaws** [comment]
You can also use the following packages references to bypass the problem:
```
    <PackageReference Include="Simple.OData.V4.Client" Version="5.*" NoWarn="NU1608" />
    <PackageReference Include="System.Text.Json" Version="6.*" NoWarn="NU1608" />
```

**Comment by pzbyszynski** [comment]
The same problem exists for `Simple.Odata.Client`

**Comment by groogiam** [comment]
Should this be closed? Looks like https://www.nuget.org/packages/Simple.OData.V4.Client/5.26.0 fixes this.

**Comment by object** [comment]
Yes I believe this one should be closed.

**Comment by davidnmbond** [comment]
Closing
