### ISSUE TITLE
Batch operations

### ISSUE THREAD

**Issue by trojanmartin** [simple-odata-client/Simple.OData.Client#849]
Hi,
First of all, I would like to say that I am really glad that this project is "alive" again. I use it a lot and I would be happy to help with development in the future too.

I created this issue to start discussion about design of the batch request in the client.
My first suggestion is about getting data in batch requests.  I found instructions in the documentation only for insertion. After studying the code, I found that the only way to do it is as follows:
 ```csharp
var client = new ODataClient("http://localhost:30012/v1/1");
var batch = new ODataBatch(client);

Task<InventoryStorage> storageTask = null;
batch += c =>
{
	storageTask = c.For<InventoryStorage>()
		.Key(1)
		.FindEntryAsync();
	return storageTask;
};

try
{
	await batch.ExecuteAsync();
	var storage = await storageTask;
}
catch (Exception e)
{
	Console.WriteLine(e);
}
```
Wouldn't it be better if the `batch.ExecuteAsync();` returns some "BatchResult" where the answers would be from the OData endpoint?

Second suggestion is about adding odata specific attributes to batch request. OData specification talks about attributes like "atomicityGroup" and  "dependsOn" and it would be great if we were able to use them in this client.

**EDIT**

> I found instructions in the documentation only for insertion. 

My fault. I already found it.

**Comment by ysmoradi** [comment]
Just to let you know that you can write your code much easier as followings:

```cs
var client = new ODataClient("http://localhost:30012/v1/1");
var batch = new ODataBatch(client);

InventoryStorage storageTask = null;

batch += async c =>
   storageTask = await c.For<InventoryStorage>()
   	.Key(1)
   	.FindEntryAsync();

await batch.ExecuteAsync();
```

**Comment by trojanmartin** [comment]
Oh thank you. I didn't realize it. In that case my first suggestion is probably irrelevant.
